#!/bin/sh

NAME=nogtk3menubar

dir=`dirname "$0"`; dir=`cd "$dir" && pwd`

if [ $# -lt 1 ]; then
 echo "Usage: $0 <command> [args [...]]" >&2
 exit 2
fi

export LD_PRELOAD="$dir/lib$NAME.so"
exec "$@"
