#!/bin/sh

dir=`dirname "$0"`; dir=`cd "$dir" && pwd`


main() {
 local dir_esc="'$(printf '%s' "$dir" | sed -e "s/'/'\\\\''/g")'"
 rm -f "$dir/qemu-system-"*
 for i in $(get_qemu_systems); do
  F_qemu_script "$i" > "$dir/$i"
  chmod +x "$dir/$i"
 done
}


get_qemu_systems() {
 _get_qemu_systems_inner | sort | uniq
}

_get_qemu_systems_inner() {
 local OIFS
 OIFS=$IFS
 IFS=:
 
 for i in $PATH; do
  IFS=$OIFS
   find "$i" -name 'qemu-system-*' -exec basename -- {} \;
  IFS=:
 done
 
 IFS=$OIFS
}


F_qemu_script() {
 cat <<"EOF"
#!/bin/sh

dir=`dirname "$0"`/..; dir=`cd "$dir" && pwd`


next() {
 local what="$1"
 
 local real_script="$(readlink -m "$0")"
 
 local oifs
 oifs=$IFS
 IFS="
"
 for i in $(which -a "$what" 2>/dev/null); do
  local real_i="$(readlink -m "$i")"
  if [ x"$real_i" != x"$real_script" ]; then
   printf '%s' "$i"
   break
  fi
 done
 
 IFS=$oifs
}


exec "$dir/run" "$(next "$(basename -- "$0")")" "$@"
EOF
}


main "$@"
